//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpModV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class analysis_status
    {
        public analysis_status()
        {
            this.proj_phases = new HashSet<proj_phases>();
        }
    
        public int id { get; set; }
        public string analysis_stat { get; set; }
    
        public virtual ICollection<proj_phases> proj_phases { get; set; }
    }
}
