//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpModV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clients
    {
        public clients()
        {
            this.clients_receipts = new HashSet<clients_receipts>();
            this.projects = new HashSet<projects>();
        }
    
        public int id { get; set; }
        public string c_name { get; set; }
        public string c_email { get; set; }
        public string tax_id { get; set; }
    
        public virtual ICollection<clients_receipts> clients_receipts { get; set; }
        public virtual ICollection<projects> projects { get; set; }
    }
}
