//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpModV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clients_receipts
    {
        public clients_receipts()
        {
            this.project_contracts = new HashSet<project_contracts>();
        }
    
        public int id { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<int> proj_id { get; set; }
        public Nullable<int> fin_rec_id { get; set; }
        public Nullable<int> pr_paymen_type { get; set; }
        public string receipt_details { get; set; }
    
        public virtual clients clients { get; set; }
        public virtual financial_records financial_records { get; set; }
        public virtual project_payment_types project_payment_types { get; set; }
        public virtual projects projects { get; set; }
        public virtual ICollection<project_contracts> project_contracts { get; set; }
    }
}
