//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpModV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contractors
    {
        public contractors()
        {
            this.contractors_receipts = new HashSet<contractors_receipts>();
        }
    
        public int id { get; set; }
        public string sc_name { get; set; }
        public string sc_email { get; set; }
        public string tax_id { get; set; }
        public Nullable<int> domain_id { get; set; }
    
        public virtual ICollection<contractors_receipts> contractors_receipts { get; set; }
        public virtual proj_domain proj_domain { get; set; }
    }
}
