//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpModV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class currency_list
    {
        public currency_list()
        {
            this.financial_records = new HashSet<financial_records>();
            this.task_funding = new HashSet<task_funding>();
            this.task_worker = new HashSet<task_worker>();
        }
    
        public int id { get; set; }
        public string cur_name { get; set; }
        public string cur_symbol { get; set; }
        public decimal cur_rate { get; set; }
    
        public virtual ICollection<financial_records> financial_records { get; set; }
        public virtual ICollection<task_funding> task_funding { get; set; }
        public virtual ICollection<task_worker> task_worker { get; set; }
    }
}
