//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpModV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class departments
    {
        public departments()
        {
            this.users = new HashSet<users>();
        }
    
        public int id { get; set; }
        public string department_name { get; set; }
    
        public virtual ICollection<users> users { get; set; }
    }
}
