//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpModV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fin_rec_status
    {
        public fin_rec_status()
        {
            this.financial_records = new HashSet<financial_records>();
        }
    
        public int id { get; set; }
        public string rec_status { get; set; }
    
        public virtual ICollection<financial_records> financial_records { get; set; }
    }
}
