//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpModV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class financial_records
    {
        public financial_records()
        {
            this.clients_receipts = new HashSet<clients_receipts>();
            this.contractors_receipts = new HashSet<contractors_receipts>();
            this.suppliers_receipts = new HashSet<suppliers_receipts>();
            this.task_funding = new HashSet<task_funding>();
        }
    
        public int id { get; set; }
        public Nullable<int> transaction_type { get; set; }
        public Nullable<int> transaction_status { get; set; }
        public decimal f_amount { get; set; }
        public Nullable<int> f_currency { get; set; }
        public string transaction_detail { get; set; }
        public int assign_by { get; set; }
        public Nullable<System.DateTime> assign_date { get; set; }
    
        public virtual ICollection<clients_receipts> clients_receipts { get; set; }
        public virtual ICollection<contractors_receipts> contractors_receipts { get; set; }
        public virtual currency_list currency_list { get; set; }
        public virtual fin_rec_status fin_rec_status { get; set; }
        public virtual fin_rec_types fin_rec_types { get; set; }
        public virtual users users { get; set; }
        public virtual ICollection<suppliers_receipts> suppliers_receipts { get; set; }
        public virtual ICollection<task_funding> task_funding { get; set; }
    }
}
