//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpModV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_types
    {
        public item_types()
        {
            this.item_list = new HashSet<item_list>();
        }
    
        public int id { get; set; }
        public string in_type { get; set; }
    
        public virtual ICollection<item_list> item_list { get; set; }
    }
}
