//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpModV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_list
    {
        public item_list()
        {
            this.proj_pricing = new HashSet<proj_pricing>();
            this.storage_receipts = new HashSet<storage_receipts>();
            this.suppliers_receipts = new HashSet<suppliers_receipts>();
            this.task_items = new HashSet<task_items>();
        }
    
        public int id { get; set; }
        public string item_name { get; set; }
        public string item_description { get; set; }
        public Nullable<int> item_type { get; set; }
    
        public virtual item_types item_types { get; set; }
        public virtual ICollection<proj_pricing> proj_pricing { get; set; }
        public virtual ICollection<storage_receipts> storage_receipts { get; set; }
        public virtual ICollection<suppliers_receipts> suppliers_receipts { get; set; }
        public virtual ICollection<task_items> task_items { get; set; }
    }
}
