//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpModV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_executive
    {
        public project_executive()
        {
            this.task_funding = new HashSet<task_funding>();
            this.task_items = new HashSet<task_items>();
            this.task_progress = new HashSet<task_progress>();
            this.task_subcontract = new HashSet<task_subcontract>();
            this.task_worker = new HashSet<task_worker>();
        }
    
        public int id { get; set; }
        public int proj_id { get; set; }
        public Nullable<int> pricing_id { get; set; }
        public string task_name { get; set; }
        public string task_description { get; set; }
        public int task_priority { get; set; }
        public System.DateTime planned_start_date { get; set; }
        public System.DateTime planned_end_date { get; set; }
        public Nullable<System.DateTime> actual_start_date { get; set; }
        public Nullable<System.DateTime> actual_end_date { get; set; }
        public Nullable<decimal> planned_resource { get; set; }
        public Nullable<decimal> planned_fund { get; set; }
        public Nullable<decimal> actual_resource { get; set; }
        public Nullable<decimal> actual_fund { get; set; }
        public int assign_by { get; set; }
        public System.DateTime assign_date { get; set; }
    
        public virtual proj_pricing proj_pricing { get; set; }
        public virtual users users { get; set; }
        public virtual projects projects { get; set; }
        public virtual ICollection<task_funding> task_funding { get; set; }
        public virtual ICollection<task_items> task_items { get; set; }
        public virtual ICollection<task_progress> task_progress { get; set; }
        public virtual ICollection<task_subcontract> task_subcontract { get; set; }
        public virtual ICollection<task_worker> task_worker { get; set; }
    }
}
