//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpModV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_contracts
    {
        public int id { get; set; }
        public int pricing_id { get; set; }
        public Nullable<decimal> total_price { get; set; }
        public Nullable<int> pric_rule { get; set; }
        public int client_rec_id { get; set; }
        public string contract_terms { get; set; }
        public int assign_by { get; set; }
        public System.DateTime assign_date { get; set; }
    
        public virtual clients_receipts clients_receipts { get; set; }
        public virtual pricing_rules pricing_rules { get; set; }
        public virtual proj_pricing proj_pricing { get; set; }
        public virtual users users { get; set; }
    }
}
