//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpModV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_status
    {
        public int id { get; set; }
        public int project_id { get; set; }
        public int p_status { get; set; }
        public bool is_paused { get; set; }
        public bool is_internal { get; set; }
        public Nullable<System.DateTime> assign_date { get; set; }
        public Nullable<int> assign_by { get; set; }
    
        public virtual init_status init_status { get; set; }
        public virtual users users { get; set; }
        public virtual projects projects { get; set; }
    }
}
