//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpModV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class proj_pricing
    {
        public proj_pricing()
        {
            this.project_contracts = new HashSet<project_contracts>();
            this.project_executive = new HashSet<project_executive>();
        }
    
        public int id { get; set; }
        public int phase_id { get; set; }
        public string item_name { get; set; }
        public Nullable<int> item_id { get; set; }
        public string item_description { get; set; }
        public int p_unit { get; set; }
        public decimal p_amount { get; set; }
        public string notes { get; set; }
        public Nullable<int> i_source { get; set; }
        public Nullable<decimal> unit_costs { get; set; }
        public decimal added_expenses { get; set; }
        public Nullable<int> tax_rule { get; set; }
        public Nullable<int> rev_rule { get; set; }
        public Nullable<int> price_rule { get; set; }
        public Nullable<int> domain_risk { get; set; }
        public Nullable<int> risk_rule { get; set; }
        public Nullable<decimal> total_costs { get; set; }
        public Nullable<decimal> total_sell_price { get; set; }
        public Nullable<int> cur_status { get; set; }
    
        public virtual common_units common_units { get; set; }
        public virtual init_risk init_risk { get; set; }
        public virtual item_list item_list { get; set; }
        public virtual item_source item_source { get; set; }
        public virtual pricing_rules pricing_rules { get; set; }
        public virtual pricing_status pricing_status { get; set; }
        public virtual proj_phases proj_phases { get; set; }
        public virtual revenue_rules revenue_rules { get; set; }
        public virtual risk_rules risk_rules { get; set; }
        public virtual tax_rules tax_rules { get; set; }
        public virtual ICollection<project_contracts> project_contracts { get; set; }
        public virtual ICollection<project_executive> project_executive { get; set; }
    }
}
