//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpModV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class proj_phases
    {
        public proj_phases()
        {
            this.item_source = new HashSet<item_source>();
            this.proj_phases1 = new HashSet<proj_phases>();
            this.proj_pricing = new HashSet<proj_pricing>();
        }
    
        public int id { get; set; }
        public int proj_id { get; set; }
        public string phase_name { get; set; }
        public string phase_description { get; set; }
        public int p_unit { get; set; }
        public decimal p_amount { get; set; }
        public string notes { get; set; }
        public Nullable<int> parent_id { get; set; }
        public bool hasChildren { get; set; }
        public System.DateTime estimated_start_date { get; set; }
        public System.DateTime estimated_end_date { get; set; }
        public Nullable<int> cur_status { get; set; }
    
        public virtual analysis_status analysis_status { get; set; }
        public virtual common_units common_units { get; set; }
        public virtual ICollection<item_source> item_source { get; set; }
        public virtual ICollection<proj_phases> proj_phases1 { get; set; }
        public virtual proj_phases proj_phases2 { get; set; }
        public virtual projects projects { get; set; }
        public virtual ICollection<proj_pricing> proj_pricing { get; set; }
    }
}
