//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpModV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_payment_types
    {
        public project_payment_types()
        {
            this.clients_receipts = new HashSet<clients_receipts>();
            this.contractors_receipts = new HashSet<contractors_receipts>();
        }
    
        public int id { get; set; }
        public string payment_types { get; set; }
    
        public virtual ICollection<clients_receipts> clients_receipts { get; set; }
        public virtual ICollection<contractors_receipts> contractors_receipts { get; set; }
    }
}
