//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpModV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class projects
    {
        public projects()
        {
            this.clients_receipts = new HashSet<clients_receipts>();
            this.contractors_receipts = new HashSet<contractors_receipts>();
            this.proj_phases = new HashSet<proj_phases>();
            this.project_executive = new HashSet<project_executive>();
            this.project_status = new HashSet<project_status>();
            this.project_users = new HashSet<project_users>();
        }
    
        public int id { get; set; }
        public string p_name { get; set; }
        public int p_domain { get; set; }
        public string p_description { get; set; }
        public Nullable<int> client_id { get; set; }
        public System.DateTime p_start_date { get; set; }
        public System.DateTime p_end_date { get; set; }
    
        public virtual clients clients { get; set; }
        public virtual ICollection<clients_receipts> clients_receipts { get; set; }
        public virtual ICollection<contractors_receipts> contractors_receipts { get; set; }
        public virtual proj_domain proj_domain { get; set; }
        public virtual ICollection<proj_phases> proj_phases { get; set; }
        public virtual ICollection<project_executive> project_executive { get; set; }
        public virtual ICollection<project_status> project_status { get; set; }
        public virtual ICollection<project_users> project_users { get; set; }
    }
}
