//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpModV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_users
    {
        public int id { get; set; }
        public int project_id { get; set; }
        public int u_id { get; set; }
        public string u_role { get; set; }
    
        public virtual projects projects { get; set; }
        public virtual users users { get; set; }
    }
}
