//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpModV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class storage_trx_types
    {
        public storage_trx_types()
        {
            this.storage_receipts = new HashSet<storage_receipts>();
        }
    
        public int id { get; set; }
        public bool trx_type { get; set; }
        public string trx_reason { get; set; }
    
        public virtual ICollection<storage_receipts> storage_receipts { get; set; }
    }
}
