//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpModV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class suppliers
    {
        public suppliers()
        {
            this.suppliers_receipts = new HashSet<suppliers_receipts>();
        }
    
        public int id { get; set; }
        public string s_name { get; set; }
        public string s_email { get; set; }
        public string tax_id { get; set; }
    
        public virtual ICollection<suppliers_receipts> suppliers_receipts { get; set; }
    }
}
