//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpModV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class task_progress
    {
        public int id { get; set; }
        public Nullable<int> task_id { get; set; }
        public bool is_contractor { get; set; }
        public Nullable<int> subcontract_id { get; set; }
        public Nullable<decimal> set_progress { get; set; }
        public int assign_by { get; set; }
        public System.DateTime assign_date { get; set; }
    
        public virtual project_executive project_executive { get; set; }
        public virtual users users { get; set; }
        public virtual task_subcontract task_subcontract { get; set; }
    }
}
