//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpModV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class task_worker
    {
        public int id { get; set; }
        public Nullable<int> task_id { get; set; }
        public string work_description { get; set; }
        public int emp_id { get; set; }
        public decimal planned_working_hours { get; set; }
        public int i_currency { get; set; }
        public decimal emp_wage_hourly { get; set; }
        public decimal actual_working_hours { get; set; }
        public int assign_by { get; set; }
        public System.DateTime assign_date { get; set; }
    
        public virtual currency_list currency_list { get; set; }
        public virtual project_executive project_executive { get; set; }
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
    }
}
