//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpModV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class task_funding
    {
        public int id { get; set; }
        public Nullable<int> task_id { get; set; }
        public string fund_description { get; set; }
        public int f_currency { get; set; }
        public decimal f_amount { get; set; }
        public int fund_rec { get; set; }
        public int assign_by { get; set; }
        public System.DateTime assign_date { get; set; }
    
        public virtual currency_list currency_list { get; set; }
        public virtual financial_records financial_records { get; set; }
        public virtual project_executive project_executive { get; set; }
        public virtual users users { get; set; }
    }
}
