//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpModV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class task_items
    {
        public int id { get; set; }
        public Nullable<int> task_id { get; set; }
        public string task_description { get; set; }
        public Nullable<int> item_id { get; set; }
        public int i_unit { get; set; }
        public decimal i_amount { get; set; }
        public Nullable<int> stk_receipt_id { get; set; }
        public Nullable<int> pur_receipt_id { get; set; }
        public int assign_by { get; set; }
        public System.DateTime assign_date { get; set; }
    
        public virtual common_units common_units { get; set; }
        public virtual item_list item_list { get; set; }
        public virtual project_executive project_executive { get; set; }
        public virtual storage_receipts storage_receipts { get; set; }
        public virtual suppliers_receipts suppliers_receipts { get; set; }
        public virtual users users { get; set; }
    }
}
