//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ErpModV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public users()
        {
            this.financial_records = new HashSet<financial_records>();
            this.project_contracts = new HashSet<project_contracts>();
            this.project_executive = new HashSet<project_executive>();
            this.project_status = new HashSet<project_status>();
            this.project_users = new HashSet<project_users>();
            this.storage_receipts = new HashSet<storage_receipts>();
            this.task_funding = new HashSet<task_funding>();
            this.task_items = new HashSet<task_items>();
            this.task_progress = new HashSet<task_progress>();
            this.task_subcontract = new HashSet<task_subcontract>();
            this.task_worker = new HashSet<task_worker>();
            this.task_worker1 = new HashSet<task_worker>();
        }
    
        public int id { get; set; }
        public string u_name { get; set; }
        public string u_password { get; set; }
        public string emp_name { get; set; }
        public string emp_email { get; set; }
        public int role_id { get; set; }
        public int department_id { get; set; }
    
        public virtual departments departments { get; set; }
        public virtual ICollection<financial_records> financial_records { get; set; }
        public virtual ICollection<project_contracts> project_contracts { get; set; }
        public virtual ICollection<project_executive> project_executive { get; set; }
        public virtual ICollection<project_status> project_status { get; set; }
        public virtual ICollection<project_users> project_users { get; set; }
        public virtual roles roles { get; set; }
        public virtual ICollection<storage_receipts> storage_receipts { get; set; }
        public virtual ICollection<task_funding> task_funding { get; set; }
        public virtual ICollection<task_items> task_items { get; set; }
        public virtual ICollection<task_progress> task_progress { get; set; }
        public virtual ICollection<task_subcontract> task_subcontract { get; set; }
        public virtual ICollection<task_worker> task_worker { get; set; }
        public virtual ICollection<task_worker> task_worker1 { get; set; }
    }
}
